/******************************************************************************
 * This file was generated by langium-cli 4.1.0.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

/* eslint-disable */
import * as langium from 'langium';

export const GraplixTerminals = {
    IDENTIFIER: /[a-zA-Z_][a-zA-Z0-9_]*/,
    WS: /\s+/,
};

export type GraplixTerminalNames = keyof typeof GraplixTerminals;

export type GraplixKeywordNames = never;

export type GraplixTokenNames = GraplixTerminalNames | GraplixKeywordNames;

export interface GraplixDocument extends langium.AstNode {
    readonly $type: 'GraplixDocument';
    statements: Array<GraplixStatement>;
}

export const GraplixDocument = {
    $type: 'GraplixDocument',
    statements: 'statements'
} as const;

export function isGraplixDocument(item: unknown): item is GraplixDocument {
    return reflection.isInstance(item, GraplixDocument.$type);
}

export interface GraplixStatement extends langium.AstNode {
    readonly $container: GraplixDocument;
    readonly $type: 'GraplixStatement';
    value: string;
}

export const GraplixStatement = {
    $type: 'GraplixStatement',
    value: 'value'
} as const;

export function isGraplixStatement(item: unknown): item is GraplixStatement {
    return reflection.isInstance(item, GraplixStatement.$type);
}

export type GraplixAstType = {
    GraplixDocument: GraplixDocument
    GraplixStatement: GraplixStatement
}

export class GraplixAstReflection extends langium.AbstractAstReflection {
    override readonly types = {
        GraplixDocument: {
            name: GraplixDocument.$type,
            properties: {
                statements: {
                    name: GraplixDocument.statements,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        GraplixStatement: {
            name: GraplixStatement.$type,
            properties: {
                value: {
                    name: GraplixStatement.value
                }
            },
            superTypes: []
        }
    } as const satisfies langium.AstMetaData
}

export const reflection = new GraplixAstReflection();
