/******************************************************************************
 * This file was generated by langium-cli 4.1.0.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

import type { LangiumSharedCoreServices, LangiumCoreServices, LangiumGeneratedCoreServices, LangiumGeneratedSharedCoreServices, LanguageMetaData, Module } from 'langium';
import { GraplixAstReflection } from './ast.js';
import { GraplixGrammar } from './grammar.js';

export const GraplixLanguageMetaData = {
    languageId: 'graplix',
    fileExtensions: ['.graplix'],
    caseInsensitive: false,
    mode: 'development'
} as const satisfies LanguageMetaData;

export const GraplixGeneratedSharedModule: Module<LangiumSharedCoreServices, LangiumGeneratedSharedCoreServices> = {
    AstReflection: () => new GraplixAstReflection()
};

export const GraplixGeneratedModule: Module<LangiumCoreServices, LangiumGeneratedCoreServices> = {
    Grammar: () => GraplixGrammar(),
    LanguageMetaData: () => GraplixLanguageMetaData,
    parser: {}
};
